#id, max file number, cmds
103000001,data,10,
103000002,data,10,
103000003,data,10,setprop sys.debug.logbuffer.path,
103000004,data,10,setprop sys.debug.stabilitylog.path,
103000005,data,10,setprop sys.debug.stabilitylog.path,
103000006,data,10,setprop sys.debug.stabilitylog.path,
103000007,blackbox,10,setprop sys.debug.datafullylog.path,
107000002,data,10,cat /proc/ufs/cmd_history cmd_history;cat /proc/ufs/uic_ec uic_ec,
109000001,data,10,setprop sys.debug.logbuffer.path,
109000002,data,10,setprop sys.debug.logbuffer.path,
110000001,data,10,setprop sys.debug.logbuffer.path,
102200001,data,10,
