#bool compress = true, bool binformat = false, bool reopen = true, bool root = false, bool loghistory = false, sublog = false
lastlog,sh /product/bin/lastlog.sh,lastlog.log,1,0,0,1,0
uboot,sh /product/bin/uboot.sh,uboot.log,1,0,0,1,0
android,/product/bin/ylogkat,android.log,1,0,1,0,0
kernel,/product/bin/ylogksg,kernel.log,1,0,1,1,0
trace,sh /product/bin/trace.sh,trace.log,
sgm,/product/bin/sgm.cpu_memory -t 1000,sgm.csv,0,1,1,0,1,0
sysinfo,sh /product/bin/sysinfo.sh,sysinfo.log,
thermal,sh /product/bin/thermal.sh,thermal.log,
ylogdebug,sh /product/bin/ylogdebug.sh,ylogdebug.log,
phoneinfo,sh /product/bin/phoneinfo.sh,phoneinfo.log,1,0,0,1,0
hcidump,hcidump,hcidump.cap,1,1,1,1,0,1
tcpdump,tcpdump -i any -p   -U -w - -s 0 ,tcpdump.cap, 0,1,1,1,0,1
trustlog,ylogkat -T,trusty.log,1,1,0,1,0,0
